Update dependencies
StackStorm/st2web pull request #1009
Opened 2023-10-20 22:24 UTC by enykeev

This PR updates softer defined \ transient dependencies and is supposed to cover for a number of open dependabot PRs in one feel swoop.

Three minor issues discovered:
- Axios no longer need data to be set on a request for `content-type` to be populated. Instead, it now sends the value provided in the `data` field verbatim and breaks auth flow. Removing previous hack fixes the problem.
- `fontello-update`'s dependency `open` has been defined very broadly and as `>=6.0.0` and switched to ESM starting 9.0.0. We do not use ESM on this project and it isn't worth to start because of a single transient dependency.
- When adding `ST2_PROTOCOL` we forgot to add it to our `serve` task. This creates a problem when you trying to run local version of st2web against dockerized st2.

In general, I have to admit, I'm beyond impressed with how well this project held up for all this years with minimal maintenance it had. Thanks to the community for keeping it afloat.

2023-10-20 22:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2web?pullRequest=1009) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2web?pullRequest=1009) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2web?pullRequest=1009) it.</sub>

2023-10-21 10:07 UTC, armab requested changes
Thanks a lot!

Could you please also update the https://github.com/StackStorm/st2web/blob/master/CHANGELOG.rst as well?

Besides that, all good.
A note for myself before merging: I'll probably need to do a quick st2web visual check to make sure nothing broke because of updates.

2023-10-21 12:42 UTC, armab commented on CHANGELOG.rst
> +* Updated various dependencies. #1009
```suggestion
* Updated various dependencies (security). #1009
```

2023-10-21 12:44 UTC, armab approved these changes
I quickly ran a few visual checks on updated st2web and found no regressions.

Thanks for updating the dependencies! 👍

2023-10-21 13:10 UTC, Kami approved these changes

2023-10-21 13:12 UTC, merged

2023-10-21 13:12 UTC, armab commented
@Kami welcome to the party! 🎉