workflow properties toggle button css issue fixes
StackStorm/st2web pull request #804
Opened 2020-10-01 13:23 UTC by shital-orchestral

![toggle-button](https://user-images.githubusercontent.com/69850047/94814809-d71b3280-040a-11eb-9e43-1c601263eb17.JPG)

2020-10-01 18:05 UTC, nmaludy requested changes
First off, thank you for the PR.

Please also include a CHANGELOG entry so we can keep track of what changes have occurred.

Thanks!

2020-10-01 18:05 UTC, nmaludy commented on modules/st2flow-details/style.css
> +} */
Please delete commented out code and ensure there is a newline at the bottom of the file.

2020-10-06 02:55 UTC, m4dcoder commented
@nmaludy This change isn't going into the master branch.  It's a fix going to be merged into the integrate-st2flow feature branch. We will have a changelog specific to the feature integration when that super PR is ready.

@shital-orchestral Just clean up the commented out code and I'll approve the change here.

2020-10-06 20:21 UTC, m4dcoder approved these changes

2020-10-06 20:21 UTC, merged