Added  task retry model feature to task properties.
StackStorm/st2web pull request #859
Opened 2021-02-18 06:40 UTC by shital-orchestral

Added **Retry Feature** as a new field under task properties.

2021-02-18 21:45 UTC, m4dcoder requested changes
@shital-orchestral A few changes

1. Can you change the default value for the `when` field to `<% failed() %>`? The default expression right now is not a valid expression for the context of retry.
2. Can you change the text for delay to `delay (seconds)`?

2021-02-19 19:45 UTC, m4dcoder requested changes
@shital-orchestral Can we make the help text appears when we hover on the input box and not hover on the field name?

2021-02-19 19:45 UTC, m4dcoder commented on modules/st2-auto-form/style.css
> +   content:"enter integer value";
Please change text to `enter expression or integer`. Can we change it to a different color (i.e. gray)?  Can it be a smaller font size?

2021-02-19 19:45 UTC, m4dcoder commented on modules/st2-auto-form/style.css
> +   content:"enter integer value";
Please change text to `enter expression or integer`. Can we change it to a different color (i.e. gray)?  Can it be a smaller font size?

2021-02-19 19:45 UTC, m4dcoder commented on modules/st2-auto-form/style.css
> + }
Can we change it to a different color (i.e. gray)?  Can it be a smaller font size?

2021-02-19 19:45 UTC, m4dcoder commented on modules/st2flow-model/schemas/orquesta.json
> +}
Add a newline?

2021-02-19 19:45 UTC, m4dcoder commented on modules/st2-auto-form/style.css
> +}
Add a newline?

2021-02-19 19:45 UTC, m4dcoder commented on modules/st2flow-details/orquesta-properties.js
> +              <StringField name="delay" value={task.retry.delay} className="delay-title" onChange={value => this.handleTaskProperty([ 'retry', 'delay(seconds)'], value)} />
Can we change field name to `delay (seconds)`?

2021-02-23 02:03 UTC, m4dcoder requested changes
@shital-orchestral What happen to the help text?

2021-02-23 02:03 UTC, m4dcoder commented on modules/st2flow-details/orquesta-properties.js
> +              <StringField name="delay(seconds)" value={task.retry.delay} className="delay-title" onChange={value => this.handleTaskProperty([ 'retry', 'delay'], value)} spec={{'default':'enter expre
Can you put a space between delay and (seconds) so it's `delay (seconds)`?

2021-03-03 01:33 UTC, m4dcoder approved these changes

2021-03-05 15:47 UTC, amanda11 commented
@m4dcoder @shital-orchestral LGTM. I found no problems with this PR, you can set negative numbers, but as per the other PR I think that is a limitation we have with other fields, and where we need to allow expression support not worth trying to resolve.

I found a bug when testing it but confirmed that that problem also exists on the master branch - so not to do with this PR. But it's an interesting bug as there are problems with Save, Execute, Save if your workflow has an input parameter: https://github.com/StackStorm/st2web/issues/862. I have confirmed that this was NOT a problem with 3.2

2021-03-29 18:02 UTC, m4dcoder commented
@amanda11 Here's a screen shot of the UI with an example where count is -100 and a validation error at the bottom of the canvas.

<img width="1680" alt="Screen Shot 2021-03-29 at 10 57 21 AM" src="https://user-images.githubusercontent.com/2767408/112879514-15be3c80-907e-11eb-8cee-18e9c906e6e0.png">

2021-03-29 19:34 UTC, amanda11 commented
Looks good - thanks for changes

2021-03-29 20:01 UTC, amanda11 approved these changes
LGTM

2021-03-29 20:03 UTC, merged