Hotkey Shortcuts and Open in New Tab/Window
StackStorm/st2web pull request #963
Opened 2022-03-07 22:20 UTC by Jappzy

Resolves [917](https://github.com/StackStorm/st2web/issues/917)

Adds hotkey shortcuts for the following functionality:
- Save (ctrl/cmd + s): Shortcut alternative to manually clicking the save button
- Open (ctrl/cmd + o): When an orquesta workflow is selected, this will open it in a new tab
- Undo/Redo (ctrl/cmd + u, shift + u): Shortcut alternative to manually clicking the undo and redo buttons in the toolbar
- Copy/Cut/Paste (ctrl/cmd + c/x/v): Copy, Cut, and Paste workflow actions in the composer workspace

Also adds click functionality for actions in the left side-panel to easily open in new tabs/windows

2022-03-17 20:56 UTC, dylan-bitovi commented
I found a bug while testing the shortcuts, `paste` seems a bit broken if you have the text window open in Workflow Composer:

Attempting to copy the last line in this picture, to the line below:
![Screen Shot 2022-03-16 at 2 37 37 PM](https://user-images.githubusercontent.com/67594226/158893488-a9eea3e6-78fd-402c-8490-7f44963b9971.png)

Results in:
![Screen Shot 2022-03-16 at 2 38 13 PM](https://user-images.githubusercontent.com/67594226/158893533-3ee43929-bd4e-4355-b86e-4817adfdc469.png)

With a module being copied as well. The paste also pastes text in the wrong location, it always pastes to the top regardless of where your cursor is; it should have been copied to line 13.

Expected result:
![Screen Shot 2022-03-16 at 2 40 49 PM](https://user-images.githubusercontent.com/67594226/158893723-99d4eceb-8201-4f5c-a5ae-9d5a08053ffe.png)

2022-03-24 08:29 UTC, pradnya-orchestral commented
@Jappzy , I have tried your shortcuts changes at my side but for redo/undo it is giving me following error. Can you check if anything missed.
![undoredo](https://user-images.githubusercontent.com/81607514/159874397-0f220ed9-fac1-42a4-a0ee-6ff7b99813e4.png)

2022-04-18 19:41 UTC, Jappzy commented
@pradnya-orchestral Good catch, I fixed this in a later commit. Are you able to re-review?

2022-05-10 15:23 UTC, mickmcgrath13 commented
@pradnya-orchestral , are you able to re-review?

@Jappzy once things look good, we'll need to merge master -> this branch

2022-05-11 10:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2web?pullRequest=963) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2web?pullRequest=963) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Jappzy<br/>:x: cognifloyd<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2web?pullRequest=963) it.</sub>

2022-09-14 06:15 UTC, nzlosh commented
@pradnya-orchestral Have you been able to review the redo/undo features since @Jappzy latest patch?

2022-09-19 19:38 UTC, cognifloyd reviewed
a couple questions

2022-09-19 19:38 UTC, cognifloyd commented on modules/st2flow-canvas/index.js
> -        handlers={{handleTaskDelete: e => {
It looks like this doesn't have a delete handler anymore. Is this on purpose?

2022-09-19 19:38 UTC, cognifloyd commented on modules/st2flow-palette/action.js
> +      <a
Why change from `div` to `a`?

2022-09-20 20:15 UTC, armab requested changes
I've tested the feature in this PR. Copy-paste worked for me and looks nice! Redo-undo worked too 👍 

Saving the workflow (cmd+s) had some issues: when opening an existing workflow `Save` shortcut worked as expected. However when creating a new workflow that wasn't saved yet the keyboard shortcut throws an exception in the console:
```
{
    "response": {
        "data": {
            "faultstring": "You must provide a name of the workflow."
        }
    }
}
```
Alternatively, doing the same 'Save' with a button click shows a warning message in UI as expected with a message:
```
Error saving workflow.: You must provide a name of the workflow.
```
Sounds like there's a missing block somewhere to try/catch.


https://user-images.githubusercontent.com/1533818/191355686-aea5621a-1cbf-418a-b4ff-3df1c0b27cb2.mov

2022-10-10 19:38 UTC, armab approved these changes
I tested it and it works as expected now, previous issues are resolved as well.

FYI cherry-picked the commits from the #991 so we'll keep all the changes in this PR.

Thanks for the follow-up fixes @cded 👍

2022-10-10 19:44 UTC, merged